import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import Ajv from 'ajv';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { openControlDatabase } from '../control-core/repository.mjs';
import { createTaskRepository } from '../control-core/task-repository.mjs';
import { atomicWriteFile, atomicWriteJson, sha256File } from '../runtime-core/atomic-store.mjs';
import { ingestJsonText, JsonIngestionError } from '../runtime-core/json-ingestion.mjs';
import { ingestStructuredOutputs } from '../runtime-core/structured-output-ingestion.mjs';
import { assertDispatchableAgent, loadActiveAgentRegistry, AgentRegistryError } from './agent-registry.mjs';

export class OrchestratorError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'OrchestratorError';
    this.code = code;
    this.details = details;
  }
}

function nowIso(clock) { return clock().toISOString(); }

function outputPath(task, schemaName) {
  const output = task.structured_outputs.find((item) => item.required && item.format === 'json'
    && item.schema_path_abs.replaceAll('\\', '/').endsWith(`/contracts/${schemaName}`));
  if (!output) throw new OrchestratorError('ORCHESTRATOR_RESULT_OUTPUT_MISSING', `task has no required ${schemaName} output`);
  return output.path_abs;
}

function compileOutputSchema(schemaPath) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const AjvClass = String(schema.$schema ?? '').includes('2020-12') ? Ajv2020 : Ajv;
  const ajv = new AjvClass({ allErrors: true, strict: true });
  addFormats(ajv);
  return ajv.compile(schema);
}

function createIntent(task, { createdAt, dispatchId, sessionId, leaseSeconds = 900 }) {
  const leaseDeadline = new Date(Date.parse(createdAt) + leaseSeconds * 1000).toISOString();
  return {
    schema_version: 1,
    record_type: 'DISPATCH_INTENT',
    dispatch_id: dispatchId,
    idempotency_key: `${task.workflow_id}/${task.task_id}/${task.run_id}/${task.assigned_agent}/${task.attempt}`,
    workflow_id: task.workflow_id,
    task_id: task.task_id,
    run_id: task.run_id,
    agent_id: task.assigned_agent,
    attempt: task.attempt,
    task_file_abs: join(task.artifact_root_abs, '.orchestrator', 'task-control-record.json'),
    input_manifest_path_abs: task.context_manifest_path_abs,
    input_manifest_sha256: sha256File(task.context_manifest_path_abs),
    session_key: `agent:${task.assigned_agent}:orchestrator:${task.workflow_id}:${task.task_id}:${task.run_id}`,
    lease_started_at: createdAt,
    lease_deadline: leaseDeadline,
    retry_count: task.attempt - 1,
    max_retries: task.max_attempts - 1,
    created_at: createdAt,
    status: 'PREPARED',
    _session_id: sessionId,
  };
}

function receipt(intent, sessionId, status, recordedAt, id) {
  return {
    schema_version: 1, record_type: 'DISPATCH_RECEIPT', receipt_id: id,
    dispatch_id: intent.dispatch_id, idempotency_key: intent.idempotency_key,
    workflow_id: intent.workflow_id, task_id: intent.task_id, run_id: intent.run_id,
    agent_id: intent.agent_id, attempt: intent.attempt, status,
    session_key: intent.session_key, session_id: sessionId, lease_deadline: intent.lease_deadline,
    input_manifest_sha256: intent.input_manifest_sha256, recorded_at: recordedAt,
  };
}

function taskMessage(task, intent) {
  const outputInstructions = task.structured_outputs.map((output) => ({
    final_output_path_abs: output.path_abs,
    staged_raw_path_abs: join(task.artifact_root_abs, '.agent-raw', `${output.path_abs.slice(task.artifact_root_abs.length).replace(/^[\\/]/u, '')}.raw`),
    format: output.format,
    required: output.required,
  }));
  return `# Local Orchestrator Task\n\nThis message is generated by the local workflow Orchestrator. It is not a request to decide workflow state.\n\n`
    + `- dispatch_id: ${intent.dispatch_id}\n- workflow_id: ${task.workflow_id}\n- task_id: ${task.task_id}\n- run_id: ${task.run_id}\n- assigned_agent: ${task.assigned_agent}\n- attempt: ${task.attempt}\n`
    + `- context_manifest_path_abs: ${task.context_manifest_path_abs}\n- worktree_path_abs: ${task.worktree_path_abs}\n- artifact_root_abs: ${task.artifact_root_abs}\n\n`
    + `Read the immutable context manifest, work only within the task's declared write boundaries, and never invoke agent dispatch, monitor APIs, Control Kernel mutations, or state/retry tools.\n`
    + `Write every declared JSON/JSONL artifact only to its staged_raw_path_abs below. Do not write the final_output_path_abs; local code performs all JSON cleaning, schema validation, atomic publishing, status transitions and retries.\n\n`
    + '```json\n' + JSON.stringify({ structured_output_staging: outputInstructions }, null, 2) + '\n```\n';
}

export async function runOpenClawAgent({ agentId, sessionId, messagePath, timeoutSeconds = 900, onStarted }) {
  return new Promise((resolveRun, rejectRun) => {
    const child = spawn('openclaw', ['agent', '--agent', agentId, '--session-id', sessionId, '--message-file', messagePath,
      '--thinking', 'off', '--timeout', String(timeoutSeconds), '--json'], { shell: true, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = ''; let stderr = ''; let started = false;
    child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => { stdout += chunk; });
    child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.once('spawn', () => {
      started = true;
      try { onStarted?.(); } catch (error) { child.kill(); rejectRun(error); }
    });
    child.once('error', (error) => rejectRun(Object.assign(error, { started, stdout, stderr })));
    child.once('close', (exitCode, signal) => resolveRun({ started, exit_code: exitCode ?? -1, signal, stdout, stderr }));
  });
}

function assertGatewayResponse(stdout) {
  try {
    const ingestion = ingestJsonText(stdout);
    const value = ingestion.value;
    const supported = value && typeof value === 'object' && !Array.isArray(value)
      && value.ok !== false
      && (value.ok === true || typeof value.reply === 'string' || typeof value.response === 'string'
        || typeof value.text === 'string' || value.status === 'ok' || value.status === 'success' || value.result !== undefined);
    if (!supported) throw new OrchestratorError('ORCHESTRATOR_GATEWAY_RESPONSE_UNSUPPORTED', 'Gateway returned an unsupported success response shape');
    return { ...ingestion, value };
  } catch (error) {
    if (error instanceof OrchestratorError) throw error;
    if (error instanceof JsonIngestionError) {
      throw new OrchestratorError('ORCHESTRATOR_GATEWAY_RESPONSE_UNSUPPORTED', `Gateway response is not one safe JSON value: ${error.diagnostic}`);
    }
    throw error;
  }
}

/**
 * Dispatch exactly one READY task. Agent selection, session identity, state
 * receipts, completion receipt and output ingestion are all derived here,
 * never from an Agent response.
 */
export async function dispatchReadyTask({ projectRoot: projectRootInput, databasePath, taskId, timeoutSeconds = 900,
  leaseSeconds = 900, clock = () => new Date(), uuid = randomUUID, runner = runOpenClawAgent } = {}) {
  const projectRoot = resolve(projectRootInput);
  const database = openControlDatabase(databasePath);
  try {
    const tasks = createTaskRepository(projectRoot, database);
    const task = tasks.get(taskId);
    if (!task) throw new OrchestratorError('TASK_NOT_FOUND', `task does not exist: ${taskId}`);
    if (task.status !== 'READY') throw new OrchestratorError('ORCHESTRATOR_TASK_NOT_READY', `task must be READY, received ${task.status}`);
    try { assertDispatchableAgent(loadActiveAgentRegistry(projectRoot), task); }
    catch (error) {
      if (error instanceof AgentRegistryError) throw new OrchestratorError(error.code, error.message);
      throw error;
    }
    const preparedAt = nowIso(clock);
    const dispatchId = `DSP-${uuid()}`;
    const sessionId = uuid();
    const intentWithInternalSession = createIntent(task, { createdAt: preparedAt, dispatchId, sessionId, leaseSeconds });
    const { _session_id: ignored, ...intent } = intentWithInternalSession;
    mkdirSync(join(task.artifact_root_abs, '.orchestrator'), { recursive: true });
    atomicWriteJson(intent.task_file_abs, task);
    const prepared = tasks.prepareDispatch(intent);
    const messagePath = join(task.artifact_root_abs, '.orchestrator', `${dispatchId}.message.md`);
    atomicWriteFile(messagePath, taskMessage(task, intent));
    let receiptsRecorded = false;
    const recordStarted = () => {
      if (receiptsRecorded) return;
      tasks.recordReceipt(receipt(intent, sessionId, 'SENT', nowIso(clock), `DRC-${uuid()}`));
      tasks.recordReceipt(receipt(intent, sessionId, 'ACKNOWLEDGED', nowIso(clock), `DRC-${uuid()}`));
      tasks.recordReceipt(receipt(intent, sessionId, 'RUNNING', nowIso(clock), `DRC-${uuid()}`));
      receiptsRecorded = true;
    };
    let run;
    try {
      run = await runner({ agentId: task.assigned_agent, sessionId, messagePath, timeoutSeconds, onStarted: recordStarted });
      if (!run.started) throw new OrchestratorError('ORCHESTRATOR_EXECUTION_FAILED', 'Gateway process exited before an execution session started');
      if (run.exit_code !== 0) throw new OrchestratorError('ORCHESTRATOR_AGENT_EXIT_NONZERO', `OpenClaw Agent exited with ${run.exit_code}`, { stderr: run.stderr.slice(-4000) });
      assertGatewayResponse(run.stdout);
      const validators = new Map();
      const accepted = ingestStructuredOutputs(task, {
        validateSchema: (schemaPath) => {
          if (!validators.has(schemaPath)) validators.set(schemaPath, compileOutputSchema(schemaPath));
          return validators.get(schemaPath);
        },
        occurredAt: nowIso(clock),
      });
      const resultPath = outputPath(task, 'result.schema.json');
      const completion = {
        schema_version: 1, record_type: 'COMPLETION_RECEIPT', completion_id: `CMP-${uuid()}`,
        dispatch_id: intent.dispatch_id, idempotency_key: intent.idempotency_key,
        workflow_id: intent.workflow_id, task_id: intent.task_id, run_id: intent.run_id,
        agent_id: intent.agent_id, attempt: intent.attempt, status: 'SUCCEEDED', session_key: intent.session_key,
        session_id: sessionId, result_path_abs: resultPath, result_sha256: sha256File(resultPath),
        error_code: null, error_message: null, completed_at: nowIso(clock),
      };
      const ingested = tasks.ingestCompletion(completion);
      return { ok: true, command: 'orchestrator-dispatch', prepared, task: ingested.task, dispatch_id: intent.dispatch_id,
        session_id: sessionId, completion: ingested.completion, result: ingested.result, gateway: { raw_sha256: assertGatewayResponse(run.stdout).raw_sha256 },
        accepted_outputs: accepted.map((item) => ({ path_abs: item.output.path_abs, receipt_path_abs: item.receipt_path_abs })), };
    } catch (error) {
      const code = error.code ?? 'ORCHESTRATOR_EXECUTION_FAILED';
      const failed = tasks.failDispatch({ dispatch_id: intent.dispatch_id, error_code: code, error_message: error.message,
        completed_at: nowIso(clock), session_id: receiptsRecorded ? sessionId : null });
      return { ok: false, command: 'orchestrator-dispatch', dispatch_id: intent.dispatch_id, task: failed.task, error: { code, message: error.message } };
    }
  } finally {
    database.close();
  }
}
